include/common.h, src/main/2824.c, src/main/323C.c
https://decomp.me/scratch/Ymk0n
=> Decompile a few funcs all referencing the same unknown structs

build.py, expected.sh, tools/first_diff.py
Usage: https://github.com/sozud/mmx4/wiki/Getting-Started#debugging-mismatches
=> Add first_diff script

include/common.h, src/main/323C.c
https://decomp.me/scratch/zRrFk
https://decomp.me/scratch/0raUr
https://decomp.me/scratch/7bgF9
=> Decompile a few functions in the callchain starting at func_800B6C74

tools/funcs_todo.py
Adjusted down to pick up this func
```
| Ovl   | Function      |   Length |   Branches | Jtbl   | WIP                             |   % |
|-------|---------------|----------|------------|--------|---------------------------------|-----|
| main  | func_8002D41C |       40 |          7 | Yes    | https://decomp.me/scratch/18Bqj |   1 |
```
=> Reduce funcs_todo threshold

include/common.h, src/main/323C.c
Includes some related cleanup and removal of the old struct.
=> Decompile func_800B6FF4

include/common.h, src/main/323C.c
Adding two initialization and reset functions that will hopefully help uncover the size and count of some of these global objects.
=> Init funcs

include/common.h, include/func_tables.h, src/main/323C.c, src/main/C49B0.c, src/main/C594C.c, src/main/C7F34.c
Includes the trivial and non-trivial update funcs as two separate commits.
=> Integrate all remaining quad update funcs

config/symbols.us.txt, include/common.h, src/main/323C.c, src/main/C49B0.c, src/main/C594C.c, src/main/C7F34.c, src/main/title_quad.c
Not sure if the `* 2` is real or not. https://decomp.me/scratch/zemvr
=> Improve docs for on screen / offset adjustment code

include/helpers/bg_is_on_screen.h, src/main/323C.c
=> Duplicated func proof-of-concept

src/main/323C.c
Cleanup from https://github.com/sozud/mmx4/pull/84
=> Decompile func_80018E50, use libcd.h constants

config/symbols.us.txt, include/common.h, src/main/323C.c
Running out of names for these... it seems to be a separate array of objects from `unk_objects` based on how it's accessed
=> Decompile func_80021CC8 and update related symbols

include/common.h, src/main/323C.c
Cool to see the symbols starting to make the code more readable!
=> Decompile func_80024E70

config/symbols.us.txt, include/common.h, include/func_tables.h, src/main/323C.c, src/main/A7878.c
Start to unravel the shape and usages of this unknown struct at VRAM 0x80173A30
=> More funcs related to unknown `QuxObj`

include/common.h, src/main/323C.c
The `Multi` is probably temporary, I think it's the `ext` part beginning but want to collect some more data on it first
=> func_800B5C60

include/common.h, src/main/C594C.c, src/main/C7F34.c, src/main/title_quad.c
Multi usage is getting messy but I'm not sure which range is the `ext` yet.
=> func_800D5D50

src/main/323C.c
These seem to allow searching either forwards or backwards to find a free object
=> Decompile func_8002AE90 and func_8002AF4C

include/common.h, include/func_tables.h, src/main/323C.c, src/main/C7F34.c
Continuation of https://github.com/sozud/mmx4/pull/149
=> Even more layer update funcs

include/common.h, include/func_tables.h, src/main/1A5BC.c, src/main/323C.c
One led to the other, hence the combined PR... hopefully we can figure out what `BarObj` is soon
=> Engine and bar update funcs

config/symbols.us.txt, src/main/323C.c
https://decomp.me/scratch/4ITkI
=> Decompile decompress_gfx

include/common.h, src/main/1A5BC.c, src/main/323C.c
This one was a pain... I don't think `BarObj` uses base but not completely sure
=> Decompile func_80017340

config/symbols.us.txt, include/common.h, src/main/1A5BC.c, src/main/323C.c, src/main/shot_objs.c
https://decomp.me/scratch/fD5hq
=> decompress_player_gfx

include/common.h, include/func_tables.h, src/main/323C.c
Trying to discover the rest of the shape of `EngineObj` and whether `D_80141BDC` is an array or struct
=> More engine update funcs

include/common.h, src/main/1A5BC.c, src/main/323C.c, src/main/BE4C0.c, src/main/shot_objs.c
Also includes some `GameInfo` update funcs
=> Use `base` for UnkObj
